### ISSUE TITLE
[Action] Like a Product

### ISSUE THREAD

**Issue by Jenny-yq** [CSCI-GA-2820-SP23-001/products#26]
**As a** customer
**I need** to be able to like a product  
**So that** it is convenient for me to find it when I want to purchase it
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a product 
 When a customer wants to mark it as 'like'
 Then this product should be tagged 'like'
```

**Comment by Div-Mehta** [comment]
Add Test portion :)
