### ISSUE TITLE
create a product that can be uniquely identified

### ISSUE THREAD

**Issue by Jenny-yq** [CSCI-GA-2820-SP23-001/products#4]
**As a** an E-commerce merchant 
**I need** to be able to create a product with information about its name, price, and description, quantity, category that can be uniquely identified in the system
**So that** consumers are able to search, see, and learn about this new product 
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a request by a merchant to add a new product to the system provided its name, price, and description, quantity and category
 When consumers search for this product
 Then they can accurately find this product and see all the information about it
```

**Comment by josephiswhere** [comment]
Lets specify what other criteria will go into adding a product. Ie. there should be a field to input the name of the product, the price, and a description. Anything else?

**Comment by Jenny-yq** [comment]
Good point! It should have been more specified. I think product name, price, and description should be the minimum. We can also let merchants include images if applicable. For some specific categories, maybe sizes (xs, s, m, l, xl, etc), colors (red, blue, green, etc), or set sizes(one piece, two pieces, one set, etc) can also be options.

**Comment by Div-Mehta** [comment]
Oops- I commented about this on another card, but we can also use the term SKU (it looks like A389274).. basically a Unique ID for every product that's under the product title. It's helpful when a customer has an older version and needs a replacement.

**Comment by josephiswhere** [comment]
Pull requested. Wating for review.
