### ISSUE TITLE
create database model and schema 

### ISSUE THREAD

**Issue by josephiswhere** [CSCI-GA-2820-SP23-001/products#6]
**As a** developer
**I need** a database to store all products and their associated states
**So that** they can be readily delivered to the server/front end

**Details and Assumptions**
- There must be some unique identifier for each product

**Acceptance Criteria**
A database instance that includes a products table with the following attributes:
1. id
2. name
3. description
4. price

**Comment by Div-Mehta** [comment]
Joseph will post the initial in the slack for us all to view!
