### ISSUE TITLE
modify description of an existing product

### ISSUE THREAD

**Issue by Jenny-yq** [CSCI-GA-2820-SP23-001/products#8]
**As a** merchant on E-commerce 
**I need** to be able to modify the description of an existing product
**So that** the information can be properly updated based on model improvement or version change
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a request from a merchant to change the description of an existing product
 When the merchant put in the updated description
 Then the current description of the product should be correctly reflected while other information stays unchanged
```

**Comment by Div-Mehta** [comment]
Maybe we also add SKU? In my supply chain experience different colors and versions may have different SKU's.. it may look like SK345908 even though description could be the same.. Could also be a different story. Let me know and I can create it!

**Comment by Div-Mehta** [comment]
Oops I see that this might belong in the "Uniquely identified" card.. I moved my comment there.. sorry! :)
